services:
  postgres:
    image: postgres:12-alpine
    environment:
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=123456
      - POSTGRES_DB=bank
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER} -d ${POSTGRES_DB}"]
      interval: 10s
      retries: 5
      start_period: 30s
      timeout: 10s
  
  api:
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      - GIN_MOD=release
      - DB_SOURCE=postgres://root:123456@postgres/bank?sslmode=disable
    ports:
      - "4000:4000"
    depends_on:
      postgres:
        condition: service_healthy
        restart: true